config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'
  

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Chrisbook</title>
	<%= stylesheet_link_tag "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" id="top"role="navigation">
  
  <div class="container">
    <div class = "navbar-header">
    
    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        
      </button>
      
      <a href="../" class="navbar-brand">ChrisBook</a>
    </div>

    <nav class="navbar-collapse bs-navbar-collapse collapse in" aria-expanded="true">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "All Statuses", feed_path %>
        </li>
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to 'Friends', user_friendships_path %></li>
        
  <li><%= link_to current_user.full_name, edit_user_registration_path %> </li>
  <li><%= link_to "Log Out", logout_path %></li>
  <% else %>
  <li><%= link_to "Register", register_path %> </li> 

   <li><%= link_to "Log in", login_path %> </li> 
  <%end%>
  </ul>
     </div>
    </nav>
     
 
</nav>
	<div class="container">
    <%flash.each do |type, message| %>
    
    <div class="alert <%= flash_class type %> alert-dismissible " role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= message %>

    </div>
  

    <% end %>  

       

    <%= yield %>
    </div>
   <%= params.inspect %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

		

	